### ISSUE TITLE
Remover dependência no five.grok

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.portal#375]
Atualmente os seguintes pacotes ainda dependem do **five.grok**:

- [x] brasil.gov.portal 1.3 (#384)
- [x] sc.microsite 1.0b4 (https://github.com/simplesconsultoria/sc.microsite/issues/2)
- [x] collective.behavior.localdiazo 1.0b3 (https://github.com/collective/collective.behavior.localdiazo/issues/11)
- [ ] brasil.gov.paginadestaque 1.2 (https://github.com/plonegovbr/brasil.gov.paginadestaque/issues/16)
- [x] sc.embedder 1.1b1 (#351)
- [x] collective.upload 1.0rc1 (#350)
- [x] collective.polls 1.6.2 (#377)
- [x] brasil.gov.tiles 1.4rc1 (https://github.com/plonegovbr/brasil.gov.tiles/issues/185)

Precisamos atualizar alguns deles e consertar outros.

É importante destacar que para nos livrar completamente do Grok os pacotes não podem depender também não do **plone.directives.form**, nem do **plone.directives.dexterity**.

**Comment by idgserpro** [comment]
> plone.directives.form
> plone.app.dexterity

Há um interesse da comunidade Plone como um todo de remover tudo que seja grok?

**Comment by hvelarde** [comment]
eu acho que não precisamos nos preocupar com esses pacotes: nossas dependências devem parar de usar plone.directives.form e devem remover o extra `[grok]` do plone.app.dexterity.

isso vamos ir descobrindo ao atualizar.

**Comment by claytonc** [comment]
> Há um interesse da comunidade Plone como um todo de remover tudo que seja grok?

https://training.plone.org/5/mastering-plone/extending.html?highlight=grok#configuring-zope-components-with-zcml

**Comment by rodfersou** [comment]
Já estamos trabalhando a um tempo com a remoção do Grok em nossos addons.

Eu sou uma das pessoas que gosta do Grok, mas percebi que o jeito que ele está implementado hoje traz mais problemas do que soluções.

Além disso o ambiente do Plone é muito extenso é bom seguir as medidas realizadas no Core do Plone para facilitar contribuições da comunidade.

**Comment by hvelarde** [comment]
aparentemente a dependência do brasil.gov.paginadestaque não poderá ser resolvida em esta iteração.

**Comment by hvelarde** [comment]
agora que o último PR foi mesclado esta issue pode ser fechada; só resta https://github.com/plonegovbr/brasil.gov.paginadestaque/issues/16 para nos livrar completamente do Grok.
