### ISSUE TITLE
Remover dependência no collective.z3cform.widgets

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.portal#381]
O collective.z3cform.widgets não está sendo mantido e gostariamos remover ele como dependência do projeto.

Atualmente os seguintes pacotes dependem dele:

- [x] collective.polls (a versão 1.10b1 remove essa dependência: #377)
- [x] brasil.gov.vcge (https://github.com/plonegovbr/brasil.gov.vcge/issues/41)
- [ ] brasil.gov.portal (tem uma customização no widget de itens relacionados que está provocando um erro)
  - [x] remover customização do widget de itens relacionados (#383)
  - [ ] remover customização do template de NITF
  - [x] adicionar mensagem de deprecation e desinstalar (pode ser realizado a futuro)

**Comment by idgserpro** [comment]
Favor também utilizar o módulo https://github.com/plonegovbr/brasil.gov.portal/blob/master/src/brasil/gov/portal/bbb.py e adicionar esse pacote para evitar erros em upgradeSteps.

https://github.com/plonegovbr/brasil.gov.portal/blob/261eb9afd532ff0eccfda652eaf5a0aa8e17284c/setup.py#L66

Outra coisa: 

> tem uma customização no widget de itens relacionados que está provocando um erro

Qual erro é esse?

**Comment by idgserpro** [comment]
Não esquecer também do upgradeStep para isso https://github.com/plonegovbr/brasil.gov.portal/commit/ab55f0fdf09201bb26e6fe9b1815e178a94d5e2c#diff-df07fa5ea3f49c3e30519609203ae037R65

**Comment by hvelarde** [comment]
acho que podemos deixar a desinstalação do pacote isso para um release futuro; por enquanto só vamos avisar que será removida a dependência mas não vamos remover ele; concordam?

de qualquer jeito o collective.z3cform.widgets ao ser desinstalado remove seu próprio browser layer.

**Comment by idgserpro** [comment]
O que você achar melhor sobre quando mexer nessa dependência pra gente está ok.

> de qualquer jeito o collective.z3cform.widgets ao ser desinstalado remove seu próprio browser layer.

Mas o problema irá persistir, pois ao remover a dependência do `buildout.cfg` a browserlayer estará persistida. O upgradeStep nos moldes como citado acima ainda é necessário.

**Comment by hvelarde** [comment]
o collective.z3cform.widgets tem que continuar como dependência de este pacote até um upgrade step desinstalar ele, ai na sequência podemos simplesmente remover completamente na versão 2.0.

**Comment by hvelarde** [comment]
pelo que vi no código na verdade a customização das views do collective.nitf não utiliza o collective.z3cform.widgets.

adicionei um upgrade step para desinstalar o pacote e remover o browser layer; isso deve ser suficiente.
